version: '3'

services:
 db:
    container_name: mychinedb
    image: 'mysql:8'
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - ./database-config.sh:/docker-entrypoint-initdb.d/database-config.sh

networks:
  default:
    external:
      name: mychine-network
